##
# source directory
##
SRC_DIR := 03_implementation
##
# output directory
##
OUT_DIR := 04_output

##
# source files
##
SRC := $(wildcard $(SRC_DIR)/*.java)

##
# classes
## 
CLS := $(SRCS:$(SRC_DIR)/%.java=$(OUT_DIR)/%.class)

##
# compiler and compiler flags
##
JC := javac
JCFLAGS := -d $(OUT_DIR)/ -cp $(SRC_DIR)/

##
# suffixes
##
.SUFFIXES: .java

##
# clean up any output files
##
clean:
    rm $(OUT_DIR)/*.class